---
name: Deploy Prefect integration-tests Workspace Flows - Stg

"on":
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: '11 16 * * 3'  # Every Wednesday at 11:11am ET (16:11 UTC)

permissions: {}

jobs:
  deploy_flows:
    name: Deploy integration-tests flows
    runs-on: ubuntu-latest
    env:
      PREFECT_CLOUD_API_URL: https://api.stg.prefect.dev/api
    permissions:
      # required to read from the repo
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Prefect
        shell: bash
        run: pip install -q prefect

      - name: Login to Prefect
        run: |
          prefect cloud login \
          --key  ${{ secrets.PREFECT_STG_INTEGRATION_TESTS_WORKSPACE_API_KEY }} \
          --workspace prefect-staging/integration-tests
        shell: bash

      - name: Deploy all flows
        shell: bash
        run: >
          prefect --no-prompt deploy
          --name "Automations - Actions"
          --name "Automations - Compound"
          --name "Automations - Proactive"
          --name "Automations - Reactive"
          --name "Automations - Sequence"
          --name "Events - Streaming"
          --name "Flow Pauses"
          --name "Flow Results"
          --name "Flow Retries With Subflows"
          --name "Flow Retries"
          --name "Hello Tasks"
          --name "Hello World - Managed"
          --name "Integration test workspace - ensure automations exist"
          --name "Secret Block"
          --name "Task Burst"
          --name "Task Results"
          --name "Task Retries"
