---
name: Deploy Prefect integration-tests (workspace) flows - prd

"on":
  push:
    branches:
      - main
  workflow_dispatch: {}

# Do not grant jobs any permissions by default
permissions: {}

jobs:
  deploy_flows:
    name: Deploy integration-tests flows
    runs-on: ubuntu-latest
    permissions:
      # required to read from the repo
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Prefect
        shell: bash
        run: pip install -q prefect

      - name: Login to Prefect
        run: |
          prefect cloud login \
          --key  ${{ secrets.PREFECT_PRD_INTEGRATION_TESTS_WORKSPACE_API_KEY }} \
          --workspace prefect-technologies/integration-tests
        shell: bash

      - name: Deploy all flows
        shell: bash
        run: >
          prefect --no-prompt deploy
          --name "Automations Tracer"
          --name "Hello Tasks - Helm"
          --name "Hello World - Helm"
